### ISSUE TITLE
Metaserver disconnects from IRC. Logs are full of Message Queue full.

### ISSUE THREAD

**Issue by SirVer** [widelands/widelands_metaserver#1]
Restarting helps, but only for a while.

**Comment by Notabilis** [comment]
Quite some time since the bug report, so maybe the relevant code has changed. But at least the current metaserver was unable to deal with restarts of the IRC server. The metaserver never reconnected to the IRC server so after a disconnect the metaserver internal message queue filled up and was never emptied again.
A branch fixing the issue should be merged and deployed now.
