### ISSUE TITLE
Game disconnect on spectator leaving

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands_metaserver#65]
On 06.08.2019 round about 9:30 pm CEST a game was closed (disconnected) for all participants when a spectator leaves the game.

There were two players: janus and ektor, and three spectators: kaputtnik, WorldSavior and Abrogans.

ektor hosts the game.

Abrogans leaved the game (don't know if he lost connection) and the result was that the whole game was disconnected.

Maybe you find some related things in the logs.

**Comment by Notabilis** [comment]
Thanks for reporting, unfortunately I have no idea what happened.
I took a look at the log files, but everything seems to be normal. Abrogans was disconnected due to some PROTOCOL_VIOLATION, which most likely only means that the client missed a ping deadline. A second later the host ektor left the game which closed the game.
Based on the metaserver logs, it looks like the problem might be in the Widelands code. I wasn't able to find a code path matching the behavior in neither the metaserver nor the client, though. In both programs only the single (spectator) client should be disconnected and the game should continue running.

**Comment by Notabilis** [comment]
Since the issue was reported a bug in Widelands has been fixed that could result in "random" data being send over the network. If this occurred here, this would explain the observed behavior.
Since that bug has been fixed, I will close this issue. Feel free to re-open it if something similar happens again.
