### ISSUE TITLE
Add-on server

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands_metaserver#71]
See widelands/widelands#3898

There are plans for an add-on system for Widelands. The server will have to provide an interface so Widelands can down-and upload add-ons.

(Disclaimer: I have no networking experience and can not imagine how such a back-end would look like in practice, nor estimate the programming effort)

**Comment by Noordfrees** [comment]
I've started writing a server for add-ons which is by and large (not entirely) functional already.   
Widelands Code is at [`Noordfrees:addons-webserver`](https://github.com/Noordfrees/widelands/tree/addons-webserver) ([implementation](https://github.com/Noordfrees/widelands/blob/addons-webserver/src/network/net_addons.cc))    
Server code (written in Java) is at branch [`webserver`](https://github.com/widelands/wl_addons_server/tree/webserver) ([implementation](https://github.com/widelands/wl_addons_server/blob/webserver/Server.java))

The server can be run locally by simply typing
```
git checkout webserver
javac *.java
java Server
```
Widelands, with this branch, currently connects to a server running on `127.0.0.1` port 7399 (unless specified otherwise with `--addon_server_ip` and/or `--addon_server_port`).

This server supports not only downloading add-ons and metadata (several times faster than in master, though I don't know how much of this increase comes from the transfer protocol and how much from the fact that I run the server on the same machine) but also writing comments, voting on add-ons, and uploading own add-ons to the server. For the latter three activities, it is of course necessary to authenticate to the server. For testing I've defined a few dummy usernames and passwords accepted by the server, but the aim is of course to have the server use the online gaming credentials, like the metaserver.

So I now have a few **questions**:

- How can the server check whether a given username is the name of a user registered on the website, and whether a given password hash is identical to that user's gaming password hash?

- In the current implementation, Widelands creates the sha1 of the password and sends this hash to the server (like I believe the network gaming code does). Is this secure? Which additional security steps must or should be taken?   (I'm not familiar at all with this networking security stuff…)

- Does the machine on which the official server will run in the end (I assume it's the same one on which the website and the metaserver live, right?) have the ability to push newly submitted add-ons and the updated metadata back to GitHub periodically (essentially, to use `git` with bunnybot's login), so that older Widelands versions will also benefit from it?

*(see also https://www.widelands.org/forum/topic/5156)*

**Comment by Notabilis** [comment]
I haven't really checked your code, but to answer your questions:
- The user accounts are stored within an SQL database on the server. For each user, the name and the SHA1-hash of the password, encoded as hex string, are stored. I haven't really worked with that part of the metaserver code, and I don't know about the specifics of the database. But the relevant metaserver code is at [1], maybe you can get some pointers out of it.
- For the metaserver, we aren't sending the hash itself over the network but are using a small protocol named CHAP [2]. When sending the hash itself, it basically becomes the password since an attacker can listen to the hash on the internet and just send the hash itself to login at later time. CHAP instead sends a random value from the server to the client, the client combines the random value with the hash of its password, and sends back the result. This way, the result send over the internet can only be used together with this one unique random value, but is useless for all future login approaches. If you have further questions about this, feel free to ask.
- I guess it will be the same server, but that is not up to me to decide. I don't see any reason why it shouldn't be possible to create such a GitHub uploader, but I am not aware of it existing yet. But I guess it could be implemented.

Just some random thoughts regarding security/networking (might already be taken care of, I haven't checked thoroughly):
- Is there a maximum file size allowed for uploading? Can a user upload a lot of small files? Basically, can a user fill up our harddisk?
- Is it possible to read, write, or delete unexpected files on the server? Are all paths/names that are received checked what they are accessing? E.g., what happens if I request or upload the addon named "/etc/passwd" ?
- Can a user run arbitrary code on the server? Can a user upload files, that are executed by someone (e.g., uploading a bash init file)?
- What about race conditions? What if two users upload the same named addon at the same time? Or add comments/votes to it? Is the same file opened in multiple threads for that?
- What if the network connection randomly aborts at some time or random/unexpected data is send? Can there be any files or memory entries left by that?
- What if a client just doesn't send anything (before login or at any later time)? Is the connection closed for such a client or will it stay open indefinitely?
- Is there any way for a client to crash the server or disrupt other connections? Are all exceptions handled "locally" for that client?

[1] https://github.com/widelands/widelands-metaserver/blob/master/wlms/userdb.go
[2] https://en.wikipedia.org/wiki/Challenge-Handshake_Authentication_Protocol

**Comment by Noordfrees** [comment]
Thanks for the explanations :) 

>     * Is there a maximum file size allowed for uploading? Can a user upload a lot of small files? Basically, can a user fill up our harddisk?

That's one thing I hadn't thought about yet. Most add-ons on the server currently are less than 1MB (in case of scripts less than 1kb) in size; the largest three are 137 MB, 71 MB and 11 MB. In principal there's no limit, so I guess I'd better enforce a hard limit of say 200 MB while uploading. (It can still be increased if this turns out to be too small). 
In which order of magnitude is storage space available on the server?

>     * Is it possible to read, write, or delete unexpected files on the server? Are all paths/names that are received checked what they are accessing? E.g., what happens if I request or upload the addon named "/etc/passwd" ?

All file paths are relative to `<WORKING_DIRECTORY>/addons/<NAME>.wad/`. I'll add some checks though that `NAME` needs to be a valid filename and that paths may not contain `..` .

>     * Can a user run arbitrary code on the server? Can a user upload files, that are executed by someone (e.g., uploading a bash init file)?

Such files would not be executed by the server, but they could be part of an add-on that is downloaded by other users. We already have a review system: all new add-ons are by default hidden from the users, and if you change the filter settings to show even these add-ons they get a prominent badge saying 
`"This add-on was not checked by the Widelands Development Team yet. We cannot guarantee that it does not contain harmful or offensive content."` 
All add-ons are timely reviewed by the dev team (currently only by me) and either marked verified or deleted.

>     * What about race conditions? What if two users upload the same named addon at the same time? Or add comments/votes to it? Is the same file opened in multiple threads for that?

I love Java's threading API… all relevant methods are declared `synchronized` to ensure that only one user at a time can make any modifications. Other threads are forced to wait.

>     * What if the network connection randomly aborts at some time or random/unexpected data is send? Can there be any files or memory entries left by that?

I *think* that I'm cleaning up in all those cases before throwing an Exception but I'll double-check this.

>     * What if a client just doesn't send anything (before login or at any later time)? Is the connection closed for such a client or will it stay open indefinitely?

As long as the client is still connected, the server waits patiently until more data is sent. As soon as the connection is closed by the client the server quits the thread. I guess it would make sense to add a timeout thread that kills connections where nothing has been received for a day or so.

>     * Is there any way for a client to crash the server or disrupt other connections? Are all exceptions handled "locally" for that client?

Each connection runs in its own thread. Each thread catches all exceptions and closes just this one exception after sending an error message to the client. Other clients are therefore unaffected.

**Comment by Noordfrees** [comment]
All implemented except for some details regarding the SQL handling. I've managed to set up a local MySQL server with a database that reflects the structure which I think is expected in `userdb.go`, and I can query a user's password from the Java server like this:

<details>
<summary>Code</summary>

```
"select id from auth_user where username='" + username + "'"
// → if successful, gives me a table with 1 row and 1 column containing the user's ID

"select password from wlggz_ggzauth where user_id=" + userID
// → if successful, gives me a table with 1 row and 1 column containing the user's password
```
</details>

The connection is initially established like this:

<details>
<summary>Code</summary>

```

Properties connectionProps = new Properties();
connectionProps.put("user", "test");
connectionProps.put("password", "123456");
java.sql.Connection database = java.sql.DriverManager.getConnection​("jdbc:mysql://localhost:3306/widelands_addons_server", connectionProps);
```
</details>

where `test` and `123456` are the username and password and `widelands_addons_server` the name of the database. On the metaserver it appears from `main.go` that these values are read from a secret config file which seems to be present only on the server. (right?)
I believe I'll need to parse this config file from the program. What structure does this file have, and what meaning do the values have? I guess that `cfg.User, cfg.Password` correspond to `test, 123456` in the above example, but what are `cfg.Database` and `cfg.Table`?

**Comment by Notabilis** [comment]
Currently there is enough free space on the server that it should be fine for quite some time.

In your first code snipped:

> containing the user's password

Actually, a string encoding of the hash of the user's password. But I think you are aware of that.

Indeed, the metaserver reads a configuration file on the server. The file looks like this:
> {
>    "database": "tcp:secretip:secretport",
>    "table": "secrettable",
>    "user": "secretuser",
>    "password": "secretpassword",
>    "backend": "mysql"
> }

When thinking about it I guess the entries in the config file are actually wrongly named. `database` should probably be `serveraddress` and `table` should be `database`.
But it should be fine if you define an own file for your server, there is no reason why they should access the same config file.

**Comment by Noordfrees** [comment]
Thank you :)

**Comment by Noordfrees** [comment]
One more question: Are the contents of the git repositories on the server ever deleted and replaced with a fresh, clean checkout, or does this never happen? 
The background is that I don't want to store the information which user voted how many stars on which add-on in the public repo, and instead store it in an untracked file that exists only on the server. Of course this will only work if I can be sure that this file will never be deleted.

**Comment by Notabilis** [comment]
I don't know about the website, but the Git repository of the metaserver isn't checked out on the server. I compile the executable on my system and copy it to the server afterwards. But I would guess that the git repository won't be deleted until you do so.

Is there a reason that you want to have this file inside the Git folder? Why not store it next to it or in /usr/local/addonserver or so? Am I guessing right that you are talking about the repository containing all addons, that is also pushed to Github for the old clients?

**Comment by Noordfrees** [comment]
Good to know thanks

> Is there a reason that you want to have this file inside the Git folder? Why not store it next to it or in /usr/local/addonserver or so? 

Good point, next to it might make more sense. I'll best make the path configurable.

> Am I guessing right that you are talking about the repository containing all addons, that is also pushed to Github for the old clients?

Correct. The https://github.com/widelands/wl_addons_server repo contains all add-ons, their translation files, as well as the Java programs for the server and the add-on catalogues. The server will commit and push local changes to GitHub frequently so everyone using older Widelands version still gets all the updates. The Transifex integration and the maintainers' review pipeline are also GitHub-based.
