### ISSUE TITLE
Port forwarding still needed for direct IP?

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands_metaserver#72]
Is it possible that the port forwarding is still required for player via direct IP instead of lobby? It seems that it doesn't work without it. It might also be possible that VPNs have a bad impact on playing via direct IP.

Reported on the forum: https://www.widelands.org/forum/topic/4911/?page=3#post-34868

**Comment by Notabilis** [comment]
This is indeed the case. If using "direct IP" the game tries to establish a direct connection, the same way as it is done in the LAN lobby. If one wants to use the netrelay to avoid port forwarding, the metaserver has to be used.

As far as I am concerned, this is intentional. This way, the "direct IP" option avoids our infrastructure (metaserver and relay) and possible problems it brings (whatever those might be). I don't see a reason to offer an option to use "direct IP" combined with the netrelay but without using the metaserver. If you want a direct connection (stressing the "direct" of "direct IP"), the relay shouldn't be involved. If you need the relay to avoid port forwardings, there is no problem with going over the metaserver (at least, no serious one that I can think of).
If there is a good reason to do so, it would be possible (with quite some work) to offer an option to use the relay without going through the metaserver lobby. Currently I don't see a reason, but that might be my lacking imagination.

**Comment by gunchleoc** [comment]
Sounds like too much work for little benefit, so let's close this. Thanks for the explanation!
